#!/bin/bash

# shellcheck disable=SC2086

get_host_status() {
    host_status=$(/usr/sbin/ampere_power_util.sh status)

    if [ "$host_status" = "gpioget failed" ]; then
        echo "Failed to get host status"
        exit 1
    fi
}

set_gpio() {
    gpio=$(gpiofind "$1")
    gpioset ${gpio}=$2
}

add_sel()
{
  MESSAGE="$1"
  LEVEL_STR="$2"
  LEVEL_ENUM="xyz.openbmc_project.Logging.Entry.Level.Error"

  case "$LEVEL_STR" in
    "Error")
      LEVEL_ENUM="xyz.openbmc_project.Logging.Entry.Level.Error"
      ;;
    "Info")
      LEVEL_ENUM="xyz.openbmc_project.Logging.Entry.Level.Informational"
      ;;
    *)
      echo "Unknown log level: $LEVEL_STR"
      ;;
  esac

  busctl call \
    xyz.openbmc_project.Logging /xyz/openbmc_project/logging \
    xyz.openbmc_project.Logging.Create Create "ssa{ss}" \
   "$MESSAGE" "$LEVEL_ENUM" 0
}

msg="Execute host power on"
echo "${msg}"
add_sel "${msg}" "Info"

set_gpio spi0-program-sel 1
set_gpio SYS_ATX_PSON_L 0
set_gpio BMC_READY 0
set_gpio POWER_OUT 0
sleep 0.2
set_gpio POWER_OUT 1

# Wait for the host to power on
sleep 2s

get_host_status

if [ "$host_status" == "on" ]
then
    echo "Host power on success"
    msg="Host system power is on"
    echo "${msg}"
    add_sel "${msg}" "Info"
    exit 0;
else
    msg="Failed to set host power on"
    echo "${msg}"
    add_sel "${msg}" "Error"
    exit 1
fi
