#!/bin/bash

get_host_status() {
    host_status=$(/usr/sbin/ampere_power_util.sh status)

    if [ "$host_status" = "gpioget failed" ]; then
        echo "Failed to get host status"
        exit 1
    fi
}

add_sel()
{
  MESSAGE="$1"
  LEVEL_STR="$2"
  LEVEL_ENUM="xyz.openbmc_project.Logging.Entry.Level.Error"

  case "$LEVEL_STR" in
    "Error")
      LEVEL_ENUM="xyz.openbmc_project.Logging.Entry.Level.Error"
      ;;
    "Info")
      LEVEL_ENUM="xyz.openbmc_project.Logging.Entry.Level.Informational"
      ;;
    *)
      echo "Unknown log level: $LEVEL_STR"
      ;;
  esac

  busctl call \
    xyz.openbmc_project.Logging /xyz/openbmc_project/logging \
    xyz.openbmc_project.Logging.Create Create "ssa{ss}" \
   "$MESSAGE" "$LEVEL_ENUM" 0
}

msg="Execute host power cycle"
echo "${msg}"
add_sel "${msg}" "Info"

# Get initial host status
get_host_status

# Current power is ON, cycle do OFF to ON. If current power is OFF then do ON
if [ "$host_status" == "on" ]; then

    /usr/libexec/phosphor-state-manager/host-poweroff

    # Set host state to off
    msg="Host system power is off"
    echo "${msg}"
    add_sel "${msg}" "Info"

    # Wait for the host to power off
    sleep 10s

    # Get host status again after attempting to power off
    get_host_status

    if [ "$host_status" != "off" ]; then
        msg="Host power cycle failed, fail to set host  power off"
        echo "${msg}"
        add_sel "${msg}" "Error"
        exit 1
    fi
fi

if [ "$host_status" != "on" ]; then

    /usr/libexec/phosphor-state-manager/host-poweron

    # Get host status again after attempting to power on
    get_host_status

    if [ "$host_status" != "on" ]; then
        msg="Host power cycle failed, fail to set host power on"
        echo "${msg}"
        add_sel "${msg}" "Error"
        exit 1
    fi

    msg="Host system power is on"
    echo "${msg}"
    add_sel "${msg}" "Info"
fi

msg="Host power cycle success"
echo "${msg}"
add_sel "${msg}" "Info"
exit 0
